services:
  postgres:
    image: postgres:16
    container_name: estoque-postgres
    environment:
      POSTGRES_DB: estoque
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - estoque_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: estoque-api
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/estoque
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  estoque_data:
